"""Minimal English/Spanish localization for the analysis pipeline and web layer.

The pipeline is deterministic Python (indicators, sentiment) plus a single LLM
step. This module centralizes the two supported languages so the deterministic
summaries, the strategist directive, and the web UI all agree on the same codes.
"""

from __future__ import annotations

from src.models.enums import Sentiment

SUPPORTED_LANGUAGES = ("en", "es")
DEFAULT_LANGUAGE = "en"

_SENTIMENT_ES = {
    Sentiment.BULLISH: "alcista",
    Sentiment.NEUTRAL: "neutral",
    Sentiment.BEARISH: "bajista",
}

_STRATEGY_DIRECTIVE = {
    "en": "Write the entire analysis in English.",
    "es": "Redacta todo el análisis en español.",
}

_DISCLAIMER = {
    "en": (
        "This report is generated by an automated multi-agent system for educational "
        "and informational purposes only. It is not financial advice. The system does "
        "not execute trades and is not connected to any broker."
    ),
    "es": (
        "Este informe lo genera un sistema multi-agente automatizado con fines "
        "educativos e informativos. No constituye asesoramiento financiero. El sistema "
        "no ejecuta operaciones y no está conectado a ningún bróker."
    ),
}


def normalize_language(language: str | None) -> str:
    """Return a supported language code, falling back to ``DEFAULT_LANGUAGE``."""
    lang = (language or "").strip().lower()
    return lang if lang in SUPPORTED_LANGUAGES else DEFAULT_LANGUAGE


def strategy_language_directive(language: str | None) -> str:
    """Sentence appended to the strategist prompt to fix the output language."""
    return _STRATEGY_DIRECTIVE[normalize_language(language)]


def sentiment_label(sentiment: Sentiment, language: str | None) -> str:
    """Human-readable sentiment word in the requested language (lowercase)."""
    lang = normalize_language(language)
    if lang == "es":
        return _SENTIMENT_ES[sentiment]
    return sentiment.value.lower()


def disclaimer_text(language: str | None) -> str:
    """Report disclaimer localized for ``language``."""
    return _DISCLAIMER[normalize_language(language)]
