"""Curated ticker catalog for the web UI.

The user-facing web app lets people pick a company by name instead of by ticker
symbol. This module maps each human-readable entry to its market symbol and
provides localized sector/description text for the EN/ES toggle.

``logo`` is a self-hosted brand image (not a monogram) served from
``/static/logos``: Simple Icons SVGs for most brands, and Google favicon
PNGs/JPEGs for brands Simple Icons no longer hosts.
"""

from __future__ import annotations

from src.utils.i18n import normalize_language


# One entry per recognizable large-cap company. ``symbol`` is what the analysis
# pipeline consumes; ``name``/``sector``/``description`` are presentation data.
CATALOG: list[dict[str, str]] = [
    {
        "symbol": "NVDA",
        "name": "NVIDIA",
        "sector": "Semiconductors",
        "color": "#76B900",
        "logo": "/static/logos/NVDA.svg",
        "description_en": "AI-accelerated computing and GPU leader.",
        "description_es": "Líder en computación acelerada por IA y GPU.",
    },
    {
        "symbol": "AAPL",
        "name": "Apple",
        "sector": "Consumer Electronics",
        "color": "#A2AAAD",
        "logo": "/static/logos/AAPL.svg",
        "description_en": "iPhone, Mac, and services ecosystem.",
        "description_es": "Ecosistema de iPhone, Mac y servicios.",
    },
    {
        "symbol": "MSFT",
        "name": "Microsoft",
        "sector": "Software & Cloud",
        "color": "#00A4EF",
        "logo": "/static/logos/MSFT.png",
        "description_en": "Cloud, productivity, and enterprise software.",
        "description_es": "Nube, productividad y software empresarial.",
    },
    {
        "symbol": "GOOGL",
        "name": "Alphabet",
        "sector": "Internet & AI",
        "color": "#4285F4",
        "logo": "/static/logos/GOOGL.svg",
        "description_en": "Search, advertising, and AI research.",
        "description_es": "Búsqueda, publicidad e investigación en IA.",
    },
    {
        "symbol": "AMZN",
        "name": "Amazon",
        "sector": "E-Commerce & Cloud",
        "color": "#FF9900",
        "logo": "/static/logos/AMZN.png",
        "description_en": "Retail and cloud infrastructure (AWS).",
        "description_es": "Comercio minorista e infraestructura en la nube (AWS).",
    },
    {
        "symbol": "META",
        "name": "Meta Platforms",
        "sector": "Social Media",
        "color": "#0866FF",
        "logo": "/static/logos/META.svg",
        "description_en": "Social platforms and the metaverse.",
        "description_es": "Plataformas sociales y el metaverso.",
    },
    {
        "symbol": "TSLA",
        "name": "Tesla",
        "sector": "Automotive & Energy",
        "color": "#E82127",
        "logo": "/static/logos/TSLA.svg",
        "description_en": "Electric vehicles and clean energy.",
        "description_es": "Vehículos eléctricos y energía limpia.",
    },
    {
        "symbol": "AMD",
        "name": "Advanced Micro Devices",
        "sector": "Semiconductors",
        "color": "#ED1C24",
        "logo": "/static/logos/AMD.svg",
        "description_en": "CPUs, GPUs, and data-center chips.",
        "description_es": "CPU, GPU y chips para centros de datos.",
    },
    {
        "symbol": "NFLX",
        "name": "Netflix",
        "sector": "Streaming",
        "color": "#E50914",
        "logo": "/static/logos/NFLX.svg",
        "description_en": "Global streaming entertainment.",
        "description_es": "Entretenimiento por streaming a nivel global.",
    },
    {
        "symbol": "JPM",
        "name": "JPMorgan Chase",
        "sector": "Banking",
        "color": "#1F6FEB",
        "logo": "/static/logos/JPM.jpg",
        "description_en": "Global banking and financial services.",
        "description_es": "Banca y servicios financieros globales.",
    },
    {
        "symbol": "V",
        "name": "Visa",
        "sector": "Payments",
        "color": "#1434CB",
        "logo": "/static/logos/V.svg",
        "description_en": "Digital payments network.",
        "description_es": "Red de pagos digitales.",
    },
    {
        "symbol": "KO",
        "name": "Coca-Cola",
        "sector": "Beverages",
        "color": "#F40009",
        "logo": "/static/logos/KO.svg",
        "description_en": "Global beverage brands.",
        "description_es": "Marcas globales de bebidas.",
    },
    {
        "symbol": "DIS",
        "name": "Walt Disney",
        "sector": "Media & Entertainment",
        "color": "#113CCF",
        "logo": "/static/logos/DIS.png",
        "description_en": "Media, parks, and streaming.",
        "description_es": "Medios, parques y streaming.",
    },
    {
        "symbol": "BA",
        "name": "Boeing",
        "sector": "Aerospace & Defense",
        "color": "#1A56DB",
        "logo": "/static/logos/BA.svg",
        "description_en": "Commercial and defense aerospace.",
        "description_es": "Aeroespacial comercial y de defensa.",
    },
    {
        "symbol": "PFE",
        "name": "Pfizer",
        "sector": "Pharmaceuticals",
        "color": "#0093D0",
        "logo": "/static/logos/PFE.png",
        "description_en": "Pharmaceuticals and vaccines.",
        "description_es": "Farmacéutica y vacunas.",
    },
    {
        "symbol": "XOM",
        "name": "Exxon Mobil",
        "sector": "Energy",
        "color": "#FE0000",
        "logo": "/static/logos/XOM.png",
        "description_en": "Integrated oil and gas.",
        "description_es": "Petróleo y gas integrados.",
    },
    {
        "symbol": "AVGO",
        "name": "Broadcom",
        "sector": "Semiconductors",
        "color": "#CC092F",
        "logo": "/static/logos/AVGO.svg",
        "description_en": "Semiconductor and infrastructure software.",
        "description_es": "Semiconductores y software de infraestructura.",
    },
    {
        "symbol": "INTC",
        "name": "Intel",
        "sector": "Semiconductors",
        "color": "#0071C5",
        "logo": "/static/logos/INTC.svg",
        "description_en": "Semiconductors and foundry services.",
        "description_es": "Semiconductores y servicios de fundición.",
    },
    {
        "symbol": "QCOM",
        "name": "Qualcomm",
        "sector": "Semiconductors",
        "color": "#3253DC",
        "logo": "/static/logos/QCOM.svg",
        "description_en": "Mobile chipsets and wireless IP.",
        "description_es": "Chipsets móviles y propiedad intelectual inalámbrica.",
    },
    {
        "symbol": "CSCO",
        "name": "Cisco Systems",
        "sector": "Networking Hardware",
        "color": "#1BA0D7",
        "logo": "/static/logos/CSCO.svg",
        "description_en": "Networking hardware and software.",
        "description_es": "Hardware y software de redes.",
    },
    {
        "symbol": "ORCL",
        "name": "Oracle",
        "sector": "Software & Cloud",
        "color": "#F80000",
        "logo": "/static/logos/ORCL.png",
        "description_en": "Database and enterprise cloud.",
        "description_es": "Base de datos y nube empresarial.",
    },
    {
        "symbol": "CRM",
        "name": "Salesforce",
        "sector": "Software & Cloud",
        "color": "#00A1E0",
        "logo": "/static/logos/CRM.png",
        "description_en": "CRM and enterprise cloud apps.",
        "description_es": "CRM y aplicaciones cloud empresariales.",
    },
    {
        "symbol": "ADBE",
        "name": "Adobe",
        "sector": "Software & Cloud",
        "color": "#FF0000",
        "logo": "/static/logos/ADBE.png",
        "description_en": "Creative and digital media software.",
        "description_es": "Software creativo y de medios digitales.",
    },
    {
        "symbol": "IBM",
        "name": "IBM",
        "sector": "Software & Cloud",
        "color": "#052FAD",
        "logo": "/static/logos/IBM.png",
        "description_en": "Enterprise IT and consulting.",
        "description_es": "TI empresarial y consultoría.",
    },
    {
        "symbol": "TSM",
        "name": "TSMC",
        "sector": "Semiconductors",
        "color": "#17365D",
        "logo": "/static/logos/TSM.png",
        "description_en": "World's largest chip foundry.",
        "description_es": "La mayor fundición de chips del mundo.",
    },
    {
        "symbol": "NOW",
        "name": "ServiceNow",
        "sector": "Software & Cloud",
        "color": "#62D84E",
        "logo": "/static/logos/NOW.png",
        "description_en": "Enterprise workflow automation.",
        "description_es": "Automatización de flujos de trabajo empresariales.",
    },
    {
        "symbol": "ACN",
        "name": "Accenture",
        "sector": "Consulting",
        "color": "#A100FF",
        "logo": "/static/logos/ACN.svg",
        "description_en": "Global consulting and services.",
        "description_es": "Consultoría y servicios globales.",
    },
    {
        "symbol": "SAP",
        "name": "SAP",
        "sector": "Software & Cloud",
        "color": "#0FAAFF",
        "logo": "/static/logos/SAP.svg",
        "description_en": "Enterprise resource planning (ERP).",
        "description_es": "Planificación de recursos empresariales (ERP).",
    },
    {
        "symbol": "UBER",
        "name": "Uber",
        "sector": "Mobility & Delivery",
        "color": "#000000",
        "logo": "/static/logos/UBER.svg",
        "description_en": "Ride-hailing and delivery.",
        "description_es": "Transporte bajo demanda y reparto.",
    },
    {
        "symbol": "ABNB",
        "name": "Airbnb",
        "sector": "Travel",
        "color": "#FF5A5F",
        "logo": "/static/logos/ABNB.svg",
        "description_en": "Short-term rental marketplace.",
        "description_es": "Marketplace de alquileres de corta estancia.",
    },
    {
        "symbol": "SHOP",
        "name": "Shopify",
        "sector": "E-Commerce & Cloud",
        "color": "#7AB55C",
        "logo": "/static/logos/SHOP.svg",
        "description_en": "E-commerce platform.",
        "description_es": "Plataforma de comercio electrónico.",
    },
    {
        "symbol": "PLTR",
        "name": "Palantir",
        "sector": "Software & Cloud",
        "color": "#000000",
        "logo": "/static/logos/PLTR.svg",
        "description_en": "Data analytics for institutions.",
        "description_es": "Analítica de datos para instituciones.",
    },
    {
        "symbol": "MCD",
        "name": "McDonald's",
        "sector": "Restaurants",
        "color": "#FFC72C",
        "logo": "/static/logos/MCD.svg",
        "description_en": "Global quick-service restaurants.",
        "description_es": "Restaurantes de servicio rápido a nivel global.",
    },
    {
        "symbol": "SBUX",
        "name": "Starbucks",
        "sector": "Restaurants",
        "color": "#006241",
        "logo": "/static/logos/SBUX.svg",
        "description_en": "Global coffeehouse chain.",
        "description_es": "Cadena global de cafeterías.",
    },
    {
        "symbol": "NKE",
        "name": "Nike",
        "sector": "Apparel",
        "color": "#111111",
        "logo": "/static/logos/NKE.svg",
        "description_en": "Athletic footwear and apparel.",
        "description_es": "Calzado y ropa deportiva.",
    },
    {
        "symbol": "WMT",
        "name": "Walmart",
        "sector": "Retail",
        "color": "#0071CE",
        "logo": "/static/logos/WMT.png",
        "description_en": "Global retail and groceries.",
        "description_es": "Retail y alimentación a nivel global.",
    },
    {
        "symbol": "COST",
        "name": "Costco",
        "sector": "Retail",
        "color": "#E31837",
        "logo": "/static/logos/COST.png",
        "description_en": "Membership warehouse retail.",
        "description_es": "Retail de almacenes con membresía.",
    },
    {
        "symbol": "HD",
        "name": "Home Depot",
        "sector": "Retail",
        "color": "#F96302",
        "logo": "/static/logos/HD.png",
        "description_en": "Home improvement retail.",
        "description_es": "Retail de mejoras para el hogar.",
    },
    {
        "symbol": "PG",
        "name": "Procter & Gamble",
        "sector": "Consumer Staples",
        "color": "#003DA5",
        "logo": "/static/logos/PG.jpg",
        "description_en": "Consumer goods brands.",
        "description_es": "Marcas de bienes de consumo.",
    },
    {
        "symbol": "PEP",
        "name": "PepsiCo",
        "sector": "Beverages",
        "color": "#004B93",
        "logo": "/static/logos/PEP.png",
        "description_en": "Snacks and beverages.",
        "description_es": "Snacks y bebidas.",
    },
    {
        "symbol": "JNJ",
        "name": "Johnson & Johnson",
        "sector": "Healthcare",
        "color": "#D51900",
        "logo": "/static/logos/JNJ.png",
        "description_en": "Pharma and medtech.",
        "description_es": "Farmacéutica y tecnología médica.",
    },
    {
        "symbol": "LLY",
        "name": "Eli Lilly",
        "sector": "Healthcare",
        "color": "#D52B1E",
        "logo": "/static/logos/LLY.png",
        "description_en": "Pharmaceuticals and diabetes care.",
        "description_es": "Farmacéutica y cuidado de la diabetes.",
    },
    {
        "symbol": "MRK",
        "name": "Merck",
        "sector": "Pharmaceuticals",
        "color": "#00857C",
        "logo": "/static/logos/MRK.svg",
        "description_en": "Pharmaceuticals and vaccines.",
        "description_es": "Farmacéutica y vacunas.",
    },
    {
        "symbol": "UNH",
        "name": "UnitedHealth",
        "sector": "Healthcare",
        "color": "#002677",
        "logo": "/static/logos/UNH.png",
        "description_en": "Health insurance and care.",
        "description_es": "Seguros de salud y atención médica.",
    },
    {
        "symbol": "C",
        "name": "Citigroup",
        "sector": "Banking",
        "color": "#004684",
        "logo": "/static/logos/C.png",
        "description_en": "Global banking and markets.",
        "description_es": "Banca y mercados globales.",
    },
    {
        "symbol": "BAC",
        "name": "Bank of America",
        "sector": "Banking",
        "color": "#E21836",
        "logo": "/static/logos/BAC.svg",
        "description_en": "Consumer and corporate banking.",
        "description_es": "Banca de consumo y corporativa.",
    },
    {
        "symbol": "WFC",
        "name": "Wells Fargo",
        "sector": "Banking",
        "color": "#D71E28",
        "logo": "/static/logos/WFC.svg",
        "description_en": "Consumer and commercial banking.",
        "description_es": "Banca de consumo y comercial.",
    },
    {
        "symbol": "GS",
        "name": "Goldman Sachs",
        "sector": "Banking",
        "color": "#7399C6",
        "logo": "/static/logos/GS.svg",
        "description_en": "Investment banking and markets.",
        "description_es": "Banca de inversión y mercados.",
    },
    {
        "symbol": "MA",
        "name": "Mastercard",
        "sector": "Payments",
        "color": "#EB001B",
        "logo": "/static/logos/MA.svg",
        "description_en": "Global payments network.",
        "description_es": "Red global de pagos.",
    },
    {
        "symbol": "AXP",
        "name": "American Express",
        "sector": "Payments",
        "color": "#2E77BC",
        "logo": "/static/logos/AXP.svg",
        "description_en": "Cards and travel services.",
        "description_es": "Tarjetas y servicios de viaje.",
    },
]

# Companies featured as large "trending now" cards ahead of the full carousel.
TRENDING_SYMBOLS: frozenset[str] = frozenset(
    {
        "NVDA",
        "AAPL",
        "MSFT",
    }
)

_SECTOR_ES = {
    "Semiconductors": "Semiconductores",
    "Consumer Electronics": "Electrónica de consumo",
    "Software & Cloud": "Software y nube",
    "Internet & AI": "Internet e IA",
    "E-Commerce & Cloud": "Comercio electrónico y nube",
    "Social Media": "Redes sociales",
    "Automotive & Energy": "Automoción y energía",
    "Streaming": "Streaming",
    "Banking": "Banca",
    "Payments": "Pagos",
    "Beverages": "Bebidas",
    "Media & Entertainment": "Medios y entretenimiento",
    "Aerospace & Defense": "Aeroespacial y defensa",
    "Pharmaceuticals": "Farmacéutica",
    "Energy": "Energía",
    "Networking Hardware": "Hardware de redes",
    "Consulting": "Consultoría",
    "Mobility & Delivery": "Movilidad y reparto",
    "Travel": "Viajes",
    "Restaurants": "Restaurantes",
    "Apparel": "Ropa y calzado",
    "Retail": "Retail",
    "Consumer Staples": "Consumo básico",
    "Healthcare": "Salud",
}


def get_catalog(language: str | None = None) -> list[dict[str, str]]:
    """Return the catalog localized for ``language`` ("en" or "es")."""
    es = normalize_language(language) == "es"
    localized: list[dict[str, str]] = []
    for entry in CATALOG:
        sector = entry["sector"]
        if es:
            sector = _SECTOR_ES.get(sector, sector)
        localized.append(
            {
                "symbol": entry["symbol"],
                "name": entry["name"],
                "sector": sector,
                "description": entry["description_es"] if es else entry["description_en"],
                "trending": entry["symbol"] in TRENDING_SYMBOLS,
                "color": entry["color"],
                "logo": entry["logo"],
            }
        )
    return localized


def is_known_symbol(symbol: str) -> bool:
    """Return True if ``symbol`` is one of the curated catalog tickers."""
    wanted = (symbol or "").strip().upper()
    return any(entry["symbol"] == wanted for entry in CATALOG)
