"""Strategy recommendation and final report models."""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, Field

from src.models.enums import Action, Sentiment
from src.models.news import NewsAnalysis
from src.models.technical import TechnicalAnalysis

DISCLAIMER = (
    "This report is generated by an automated multi-agent system for educational "
    "and informational purposes only. It is not financial advice. The system does "
    "not execute trades and is not connected to any broker."
)


class StrategyRecommendation(BaseModel):
    """The strategist agent's final BUY/HOLD/SELL decision."""

    ticker: str
    action: Action = Action.HOLD
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    summary: str = ""
    bullish_factors: list[str] = Field(default_factory=list)
    bearish_factors: list[str] = Field(default_factory=list)
    technical_signal: Sentiment = Sentiment.NEUTRAL
    news_signal: Sentiment = Sentiment.NEUTRAL
    risk_factors: list[str] = Field(default_factory=list)
    invalidating_conditions: list[str] = Field(default_factory=list)
    timestamp: datetime | None = None


class MarketReport(BaseModel):
    """Top-level report returned to the caller / printed by the CLI."""

    execution_id: str
    ticker: str
    timestamp: datetime
    model: str
    market_data_timestamp: datetime | None = None
    news_search_timestamp: datetime | None = None
    price: float | None = None
    high_52w: float | None = None
    low_52w: float | None = None
    news_analysis: NewsAnalysis | None = None
    technical_analysis: TechnicalAnalysis | None = None
    recommendation: StrategyRecommendation
    sources: list[str] = Field(default_factory=list)
    depth: str = "standard"
    disclaimer: str = DISCLAIMER
